[developement] kafka status export
dojot/dojot-microservice-sdk-js pull request #30
Opened 2020-10-29 17:44 UTC by jonaphael

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2020-10-29 18:49 UTC, eduardogmisiuk requested changes
You should add the new functionality in the examples too, but it's nice to me.

2020-10-29 18:49 UTC, eduardogmisiuk commented on package.json
> +  "version": "0.1.7",
Don't change the version, this is done only when creating a new release.

2020-10-29 18:50 UTC, jonaphael commented on package.json
> +  "version": "0.1.7",
great!

2020-11-03 12:08 UTC, mprevide commented on lib/kafka/Helper.js
> +    reject(new Error('Internal error while getting kafka metadata.'));
The msg here should be different

2020-11-03 16:48 UTC, rascaraficci requested changes
I think we could make the getStatus function simpler, returning just connected or not. I left some ideas of how to achieve this.

2020-11-03 16:48 UTC, rascaraficci commented on lib/kafka/Helper.js
> +    reject(new Error('Internal error while getting kafka metadata.'));
I agree with Mariane.

2020-11-03 16:48 UTC, rascaraficci commented on lib/kafka/Helper.js
> +const getStatus = (kafkaObject, timeout = 3000) => new Promise((resolve, reject) => {
I think the method could be simpler, i.e, return connected or not.

2020-11-03 16:48 UTC, rascaraficci commented on lib/kafka/Helper.js
> +      objectStatus.details = { metadata };
this line should be removed. This result won't be analyzed by the caller.

2020-11-03 16:48 UTC, rascaraficci commented on lib/kafka/Helper.js
> +      reject(new Error(`Internal error while getting kafka metadata. ${err}`));
I think we should resolve here with connected = false, because we are using the success/failure of this call to determine whether the consumer/producer is connected or not.

2020-11-03 16:48 UTC, rascaraficci commented on lib/kafka/Helper.js
> +  if (!kafkaObject) {
I think we shouldn't check anything once it is an internal method and the result of this promised is being handled out of the SDK.

2020-11-06 12:44 UTC, rascaraficci approved these changes
It looks good to me!

2020-11-06 13:01 UTC, eduardogmisiuk approved these changes

2020-11-06 14:49 UTC, merged