[develpment] added deinit func to consumer
dojot/dojot-microservice-sdk-js pull request #39
Opened 2020-11-16 11:54 UTC by jonaphael

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2020-11-16 12:14 UTC, mprevide commented on lib/kafka/Consumer.js
> +  deinit() {
deinit? Maybe disconnect? unsubscribeAll?

2020-11-16 12:16 UTC, mprevide commented on examples/consumer/sample.js
> +  }, 30000); // 300000
Remove // 300000

2020-11-16 12:34 UTC, eduardogmisiuk commented on examples/consumer/sample.js
> +  }, 30000); // 300000
Misleading comment or wrong interval? Remove the `// 300000` comment.

2020-11-16 12:34 UTC, eduardogmisiuk commented on lib/kafka/Consumer.js
> +      }
As I understand Promises, when you call reject or resolve, it already returns the function. Are all those returns in those functions really needed?

2020-11-16 12:35 UTC, eduardogmisiuk commented
Change the branch from `master` to `development` and correct the title `develpment` to `dev`.

2020-11-16 13:04 UTC, rascaraficci requested changes
I left some comments.

2020-11-16 13:04 UTC, rascaraficci commented on lib/kafka/Consumer.js
> +        const disconnectTimeout = setTimeout(() => {
I think it is better to set the timer before call unsubscribe().

2020-11-16 13:41 UTC, mprevide commented on lib/kafka/Consumer.js
> +  deinit() {
finish looks better

2020-11-16 15:54 UTC, jonaphael commented on lib/kafka/Consumer.js
> +  deinit() {
changed to finish!

2020-11-16 16:47 UTC, eduardogmisiuk commented on lib/kafka/Consumer.js
> +      }
Yes, that's true, I didn't know that. For someone with any doubts about this: https://stackoverflow.com/a/32536083

2020-11-17 11:43 UTC, eduardogmisiuk commented on test/unit/kafka/Consumer.test.js
> +test('Finish - success even consumer not ready', async () => {
succeed even when the consumer is not ready

2020-11-17 11:43 UTC, eduardogmisiuk commented on test/unit/kafka/Consumer.test.js
> +  // consumer.isReady = true;
Remove it.

2020-11-17 11:43 UTC, eduardogmisiuk commented on test/unit/kafka/Producer.test.js
> +    it('Should create a producer connect and fail produce', () => {
should create a producer connection and fail to produce

2020-11-17 11:51 UTC, rascaraficci reviewed
I left some comments.

2020-11-17 11:51 UTC, rascaraficci commented on lib/kafka/CommitManager.js
> +  finish() {
Why don't to try to commit the messages here?

2020-11-17 11:51 UTC, rascaraficci commented on lib/kafka/Consumer.js
> +        this.consumer.unsubscribe();
Will this unsubscribe all topics of the consumer? I didn't scrutinize the unsubscribe() method, but seems it is necessary some changes.

2020-11-17 11:51 UTC, rascaraficci commented on test/unit/kafka/Consumer.test.js
> +  consumer.unsubscribe = jest.fn();
It is not a good idea to mock unsubscribe() and disconnect(), you should mock the dependencies of the consumer class.

2020-11-17 11:51 UTC, rascaraficci commented on test/unit/kafka/Consumer.test.js
> +  consumer.unsubscribe = jest.fn();
The same comment above.

2020-11-17 11:57 UTC, jonaphael commented on lib/kafka/Consumer.js
> +        this.consumer.unsubscribe();
Yes its unsubscribe from all topics of the consumer. 
For more details, you can check here `https://github.com/Blizzard/node-rdkafka#standard-api-1`

2020-11-17 14:22 UTC, eduardogmisiuk approved these changes
LGTM!

2020-11-17 14:26 UTC, eduardogmisiuk reviewed
I left one comment.

2020-11-17 14:26 UTC, eduardogmisiuk commented on test/unit/kafka/Consumer.test.js
> +  consumer.commitManager = new CommitManagerMock();
As I could see, you did not mock this dependency.

2020-11-17 14:30 UTC, rascaraficci reviewed
I think that the finish() method of the consumer should also clean its internal data structures too. There are some subscriptions lists and queues. One possibility to clean the internal subscriptions would be call the unsubscribe() instead of the consumer.unsubscribe(), but would be necessary to change the  method unsubscribe().

2020-11-17 15:08 UTC, jonaphael commented on test/unit/kafka/Consumer.test.js
> +  consumer.commitManager = new CommitManagerMock();
It's been mocked on line 5
`jest.mock('kafka/CommitManager.js');`

2020-11-17 15:10 UTC, eduardogmisiuk commented on test/unit/kafka/Consumer.test.js
> +  consumer.commitManager = new CommitManagerMock();
That's true, didn't see it

2020-11-17 15:16 UTC, jonaphael commented
> I think that the finish() method of the consumer should also clean its internal data structures too. There are some subscriptions lists and queues. One possibility to clean the internal subscriptions would be call the unsubscribe() instead of the consumer.unsubscribe(), but would be necessary to change the method unsubscribe().

The disconnect method fires the `disconnected` event, I'll clean up internal data structures in a callback attached to this event, and it will not be necessary to change or implement a new `unsubscribe` function.

2020-11-17 16:12 UTC, rascaraficci approved these changes
It looks good to me!

2020-11-17 16:34 UTC, eduardogmisiuk approved these changes
LGTM!

2020-11-17 16:34 UTC, merged